name: Unit Tests

on: 
  workflow_dispatch:
  workflow_call:
  push:

jobs:
  test:
    name: Unit Tests (${{ matrix.exe }} - ${{ matrix.version }})
    runs-on: windows-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        exe: ['AutoHotkey64.exe', 'AutoHotkey32.exe']
        version: ['latest']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install AutoHotkey V2
        id: ahk
        uses: holy-tao/install-autohotkey@v1.3.0
        with:
          version: ${{ matrix.version }}

      - name: Install Required Libraries
        uses: actions/checkout@v6
        with:
          repository: holy-tao/AhkExtensions
          path: tests\Lib\Extensions
          submodules: false

      - name: Run Unit Tests
        working-directory: tests
        shell: powershell
        run: ${{ matrix.exe }} /ErrorStdOut RunTests.ahk

      - name: Publish Test Results
        if: always()
        uses: mikepenz/action-junit-report@v6
        with:
          report_paths: tests/junit.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Test Results (${{ matrix.exe }} - ${{ matrix.version }})
          detailed_summary: true
          include_time_in_summary: true
          include_passed: true
